"""product_ingredient_units

Revision ID: 0c778a903fb3
Revises: 2c37689e0156
Create Date: 2024-04-06 18:51:55.976908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0c778a903fb3'
down_revision: Union[str, None] = '2c37689e0156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units_of_measurement',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('abbreviation', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('abbreviation'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('ingredients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('measure_unit_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['measure_unit_id'], ['units_of_measurement.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('owner_id', sa.UUID(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product_ingredient_association',
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('ingredient_id', sa.Integer(), nullable=False),
                    sa.Column('nominal_coefficient', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('product_id', 'ingredient_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_ingredient_association')
    op.drop_table('product')
    op.drop_table('ingredients')
    op.drop_table('units_of_measurement')
    # ### end Alembic commands ###
