"""order_items

Revision ID: 7c6bd79c0c0e
Revises: 4da0aac7c342
Create Date: 2024-04-20 13:20:03.552056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7c6bd79c0c0e'
down_revision: Union[str, None] = '4da0aac7c342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('created', sa.TIMESTAMP(), nullable=True),
                    sa.Column('modified', sa.TIMESTAMP(), nullable=True),
                    sa.Column('date_deliver', sa.TIMESTAMP(), nullable=True),
                    sa.Column('deadline', sa.TIMESTAMP(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.Column('ingredient_id', sa.Integer(), nullable=True),
                    sa.Column('consumer_id', sa.UUID(), nullable=True),
                    sa.Column('producer_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['consumer_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
                    sa.ForeignKeyConstraint(['producer_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['status'], ['order_status.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    # ### end Alembic commands ###
