"""order_items_have_status_id

Revision ID: 17af7f7b8bd1
Revises: 17060d1127ba
Create Date: 2024-04-22 13:40:45.367186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '17af7f7b8bd1'
down_revision: Union[str, None] = '17060d1127ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_item_status_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order_status', ['status_id'], ['id'])
    op.drop_column('order_item', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_status_fkey', 'order_item', 'order_status', ['status'], ['id'])
    op.drop_column('order_item', 'status_id')
    # ### end Alembic commands ###
