name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Semantic Version using GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Inserting FullSemVer into the build
        run: |
          sed -i "s/BUILD_FULL_SEMANTIC_VERSION = \"dev-build\"/BUILD_FULL_SEMANTIC_VERSION = \"${{ steps.gitversion.outputs.FullSemVer }}\"/" ${{ github.workspace }}/app/configuration/settings.py

      - name: Parsing BACKEND_ENVIRONMENT_VARIABLES
        run: |
          echo INLINE_BACKENV="${{ secrets.BACKEND_ENVIRONMENT_VARIABLES }}" | tr '\n' ' ' >> "$GITHUB_ENV"

      - run: echo "$INLINE_BACKENV"

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App [v${{ steps.gitversion.outputs.SemVer }}]
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ vars.AZURE_ACR_NAME }}
          containerAppName: ${{ vars.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP }}
          ingress: "external"
          targetPort: 8000
          imageToBuild: ${{ vars.AZURE_ACR_NAME }}.azurecr.io/${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.gitversion.outputs.SemVer }}
          environmentVariables: ${{ vars.INLINE_BACKENV }}
 