name: Docker Image Building and Running Test

on:
  pull_request:
    types:
    - opened
    - edited
    - reopened
    - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Docker image build test
      run: docker build -t farmservice-backend-test .

    - name: Export variables into .env
      run: echo ${{ secrets.BACKEND_ENVIRONMENT_VARIABLES }} >> .env

    - name: Docker container run test
      run: |
        docker run --name farmservice-backend-test --env-file ./.env -p 8000:8000 -d farmservice-backend-test

    - name: Docker container run check
      run: |
        docker ps

    - name: Test container's response
      run: |
        URL="http://localhost:8000/api/v1/test"
        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "$URL")
        if [ $? -ne 0 ]; then
          echo "Error: Failed to reach $URL" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        if [[ ! $STATUS_CODE =~ ^2 ]]; then
          echo "Error: Received HTTP status code $STATUS_CODE" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        echo "Success: Received HTTP status code $STATUS_CODE" >> $GITHUB_STEP_SUMMARY
